print("원금 = ", end="")
money=int(input())
print("이율 = ", end="")
rate=int(input())
money*=(1+rate/100)
print("1년차 = %d" %money)
money*=(1+rate/100)
print("2년차 = %d" %money)
money*=(1+rate/100)
print("3년차 = %d" %money)